### ISSUE TITLE
Error: spawn yt-dlp EACCES

### ISSUE THREAD

**Issue by Josanshuo** [sooros5132/yt-dlp-web#12]
Using the latest docker image and run it inside a NAS.

The website front end is working, but when click download, it shows the followng errors:

```

[32m[1m鉁?[22m[39m Starting...
--

[32m[1m鉁?[22m[39m Ready in   286ms
 
[1m[38;2;173;127;168m鈻?Next.js 14.2.13[39m[22m
 
-   Local:        http://localhost:3000
-   Network:      http://0.0.0.0:3000
 
[32m[1m鉁?[22m[39m Starting...
 
[32m[1m鉁?[22m[39m Ready in   154ms
 
[31m[auth][error][0m   MissingSecret: Please define a `secret`. Read more at   https://errors.authjs.dev#missingsecret
 
at /app/.next/server/chunks/881.js:368:50420
at or (/app/.next/server/chunks/881.js:368:53014)
at runNextTicks (node:internal/process/task_queues:60:5)
at listOnTimeout (node:internal/timers:538:9)
at process.processTimers (node:internal/timers:512:7)
new   process, `undefined`
Error: spawn yt-dlp EACCES
[90m    at ChildProcess._handle.onexit   (node:internal/child_process:284:19)[39m
[90m    at onErrorNT   (node:internal/child_process:477:16)[39m
[90m    at process.processTicksAndRejections   (node:internal/process/task_queues:82:21)[39m {
errno: [33m-13[39m,
code: [32m'EACCES'[39m,
syscall: [32m'spawn   yt-dlp'[39m,
path: [32m'yt-dlp'[39m,
 
spawnargs: [
[32m'--verbose'[39m,
[32m'--progress'[39m,
[32m'--no-continue'[39m,
[32m'--windows-filenames'[39m,
[32m'--merge-output-format'[39m,
[32m'mp4'[39m,
[32m'-P'[39m,
[32m'/downloads'[39m,
[32m'--print'[39m,
[32m'after_move:filepath'[39m,
[32m'-f'[39m,
[32m'bv+ba/b'[39m,
[32m'--no-playlist'[39m,
[32m'-o'[39m,
[32m'%(title)s   (%(id)s).%(ext)s'[39m,
 
[32m'<YOUTUBE URL>'[39m
 
]
 
}

```

I could run the `yt-dlp --version` inside the docker container `bin/sh`, so it is not related the permission.

Wondering if I missed any environment variables?

**Comment by sooros5132** [comment]
The only environmental variables that can be set are the environmental variable settings required to login.

When I look at `new process, undefined`, it fails to run and comes up as `undefined`, and I don't know exactly why.
I checked the code when download it and when check version, and there was no difference.

Once again, use `id -u` and `id -g` to get the user id and group id, and set it in the `docker-compose.yml` file
And make sure you have permission to read and write the downloads and cache folders

```YML
# docker-compose.yml
# ~
    user: 1000:1000 # User Id, Group Id Setting
# ~
```

**Comment by sooros5132** [comment]
If I try with this option turned off, do I still get an error?
<img width="408" alt="SCR-20241014-rekc" src="https://github.com/user-attachments/assets/6b31ae54-6308-4059-b48e-6afd19a10940">

**Comment by Josanshuo** [comment]
Thank you @sooros5132 for the quick response. If I uncheck the `Download now`, there is no errors in the log. 

And you are right that the container doesn't have access to my download folder, changing it to another folder solves the issue.
