### ISSUE TITLE
Mobile playback

### ISSUE THREAD

**Issue by Josanshuo** [sooros5132/yt-dlp-web#17]
Currently on mobile it only supports download videos, but doesn't allow playback with error `The file does not exist or cannot be played`.

Wondering will it be supported in future version? Also curious what is the challenges of enabling the playback?

**Comment by sooros5132** [comment]
Most likely, the reason you can't play it is a codec issue or a download issue.

I've tried downloading a YouTube playlist and playing the videos within it, and it seems to be working fine.
If you're trying to play it in the Safari browser, it doesn't support VP9 and H265 codecs.
Chrome browser supports most codecs, so check it out!

+ I'll also add the ability to play videos inside a playlist on yt-dlp-web

**Comment by Josanshuo** [comment]
Thank you sooros! I will try the new version with the play list play.

However even using the Chrome on iPhone still has the same error:![image](https://github.com/user-attachments/assets/64460e1c-26d7-4a81-bd19-e233dde2dbe9)

I tried on iPad, the issue is the same. It maybe only my device setting problem, will check further.

**Comment by Josanshuo** [comment]
Thank you sooros! I will try the new version with the play list play.

However even using the Chrome on iPhone still has the same error: 
![388185688-b3dbe69c-429d-47cd-8a08-ac746fe2af7c](https://github.com/user-attachments/assets/8b727953-b10f-463e-8f07-9f1d9cfb72f1)


I tried on iPad, the issue is the same. It maybe only my device setting problem, will check further.

**Comment by sooros5132** [comment]
> Thank you sooros! I will try the new version with the play list play.
> 
> However even using the Chrome on iPhone still has the same error: ![388185688-b3dbe69c-429d-47cd-8a08-ac746fe2af7c](https://private-user-images.githubusercontent.com/42686700/388187599-8b727953-b10f-463e-8f07-9f1d9cfb72f1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjE1MjIsIm5iZiI6MTczMjEyMTIyMiwicGF0aCI6Ii80MjY4NjcwMC8zODgxODc1OTktOGI3Mjc5NTMtYjEwZi00NjNlLThmMDctOWYxZDljZmI3MmYxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNjQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTI3ZjMwMjczNzI2M2MwMGZlODQ5ZjM2M2Y1ODhiMTAwYjMwZTIxNGJmNjZkODczNzA3MGI1MjJlMzdjOTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-sFRBnkJ4seh2a_bDXgNMDdre53QPHBGZqXmKkS2Kpk)
> 
> I tried on iPad, the issue is the same. It maybe only my device setting problem, will check further.


If you're on an iPhone or iPad, it won't play even if you're using Chrome. I'm having the same problem 😭

As an alternative, I use the following method
You can connect to players such as nplayer or infuse with ftp or smb.
I also like jellyfin, which makes media servers.

**Comment by Josanshuo** [comment]
Thank you for the suggestion! Very useful and helpful!
