### ISSUE TITLE
iOS ShortCut "Don't open browser and download now" option causes 2 videos to be downloaded

### ISSUE THREAD

**Issue by jonatino** [sooros5132/yt-dlp-web#7]
Share a link to the iOS shortcut and select the 3rd option "Don't open browser and download now". It causes 2 duplicate videos to be downloaded every time.

**Comment by sooros5132** [comment]
hello. Thank you for reporting the error.

I checked and it looks like the shortcode was changed internally.
I noticed that the shortcut was sending 2 download requests, and fixed it.
Please replace it with the new version below and try again!

[https://www.icloud.com/shortcuts/8b038411c518474bbfe566f9fbe1e046](https://www.icloud.com/shortcuts/8b038411c518474bbfe566f9fbe1e046)

**Comment by jonatino** [comment]
That worked perfectly. Thank you for fixing it! Closing.
